apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: react-app-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
